unlet! skip_defaults_vim
source $VIMRUNTIME/defaults.vim

" enter the current millenium
set nocompatible

" enable syntax and plugins
syntax enable
filetype plugin on

" line numbering
set number relativenumber

augroup numbertoggle
    autocmd!
    autocmd BufEnter,FocusGained,InsertLeave    * set relativenumber
    autocmd BufLeave,FocusLost,InsertEnter      * set norelativenumber
augroup END

" softtabs, 2 spaces
set tabstop=2
set shiftwidth=2
set shiftround
set expandtab

" colour scheme
colorscheme delek
" colorscheme elflord
" colorscheme koehler
" colorscheme peachpuff
